version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16

  pre_build:
    commands:
      - echo Installing dependencies
      - npm install

  build:
    commands:
      - echo Running tests
      - npm test
      - echo test passed

  post_build:
    commands:
      - echo success building docker image
      -printf 'success' > imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json
