version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16

  pre_build:
    commands:
      - echo Installing dependencies
      - npm install

  build:
    commands:
      - echo Running tests
      - npm test
      - echo Building and tagging Docker image
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 463519496884.dkr.ecr.us-east-1.amazonaws.com
      - docker build -t node-api .
      - docker tag node-api:latest 463519496884.dkr.ecr.us-east-1.amazonaws.com/node-api:latest

  post_build:
    commands:
      - echo Pushing to ECR
      - docker push 463519496884.dkr.ecr.us-east-1.amazonaws.com/node-api:latest
      - printf '[{"name":"node-api","463519496884.dkr.ecr.us-east-1.amazonaws.com/node-api:latest"}]' > imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json
